package com.charmnight.linkgraph.application.model

import com.charmnight.linkgraph.workbench.QaMode

enum class AsyncRequestPhase {
    IDLE,
    RUNNING,
    SUCCEEDED,
    FAILED,
    TIMED_OUT,
}

enum class AsyncRequestExecutionMode {
    DISABLED,
    LOCAL_RULE,
    REMOTE_READY,
    REMOTE_FALLBACK,
}

data class AsyncRequestState(
    val phase: AsyncRequestPhase = AsyncRequestPhase.IDLE,
    val requestId: Long? = null,
    val scene: String? = null,
    val executionMode: AsyncRequestExecutionMode? = null,
    val statusMessage: String? = null,
    val errorMessage: String? = null,
    val detailMessage: String? = null,
    val startedAtEpochMillis: Long? = null,
    val finishedAtEpochMillis: Long? = null,
    val streaming: Boolean = false,
    val fallbackUsed: Boolean = false,
    val streamPhase: String? = null,
    val previewText: String? = null,
    val previewUpdatedAtEpochMillis: Long? = null,
    val finalizingStructuredResult: Boolean = false,
    val providerLabel: String? = null,
    val model: String? = null,
    val endpointSummary: String? = null,
    val promptPreviewAvailable: Boolean = false,
    val requestedMode: QaMode? = null,
    val effectiveMode: QaMode? = null,
) {
    companion object {
        fun running(
            requestId: Long? = null,
            scene: String? = null,
            executionMode: AsyncRequestExecutionMode? = null,
            statusMessage: String? = null,
            detailMessage: String? = null,
            startedAtEpochMillis: Long = System.currentTimeMillis(),
            streaming: Boolean = false,
            streamPhase: String? = null,
            previewText: String? = null,
            previewUpdatedAtEpochMillis: Long? = null,
            finalizingStructuredResult: Boolean = false,
            providerLabel: String? = null,
            model: String? = null,
            endpointSummary: String? = null,
            promptPreviewAvailable: Boolean = false,
            requestedMode: QaMode? = null,
            effectiveMode: QaMode? = null,
        ) = AsyncRequestState(
            phase = AsyncRequestPhase.RUNNING,
            requestId = requestId,
            scene = scene,
            executionMode = executionMode,
            statusMessage = statusMessage,
            detailMessage = detailMessage,
            startedAtEpochMillis = startedAtEpochMillis,
            streaming = streaming,
            streamPhase = streamPhase,
            previewText = previewText,
            previewUpdatedAtEpochMillis = previewUpdatedAtEpochMillis,
            finalizingStructuredResult = finalizingStructuredResult,
            providerLabel = providerLabel,
            model = model,
            endpointSummary = endpointSummary,
            promptPreviewAvailable = promptPreviewAvailable,
            requestedMode = requestedMode,
            effectiveMode = effectiveMode,
        )

        fun succeeded(
            requestId: Long? = null,
            scene: String? = null,
            executionMode: AsyncRequestExecutionMode? = null,
            statusMessage: String? = null,
            detailMessage: String? = null,
            startedAtEpochMillis: Long? = null,
            finishedAtEpochMillis: Long = System.currentTimeMillis(),
            streaming: Boolean = false,
            fallbackUsed: Boolean = false,
            streamPhase: String? = null,
            previewText: String? = null,
            previewUpdatedAtEpochMillis: Long? = null,
            finalizingStructuredResult: Boolean = false,
            providerLabel: String? = null,
            model: String? = null,
            endpointSummary: String? = null,
            promptPreviewAvailable: Boolean = false,
            requestedMode: QaMode? = null,
            effectiveMode: QaMode? = null,
        ) = AsyncRequestState(
            phase = AsyncRequestPhase.SUCCEEDED,
            requestId = requestId,
            scene = scene,
            executionMode = executionMode,
            statusMessage = statusMessage,
            detailMessage = detailMessage,
            startedAtEpochMillis = startedAtEpochMillis,
            finishedAtEpochMillis = finishedAtEpochMillis,
            streaming = streaming,
            fallbackUsed = fallbackUsed,
            streamPhase = streamPhase,
            previewText = previewText,
            previewUpdatedAtEpochMillis = previewUpdatedAtEpochMillis,
            finalizingStructuredResult = finalizingStructuredResult,
            providerLabel = providerLabel,
            model = model,
            endpointSummary = endpointSummary,
            promptPreviewAvailable = promptPreviewAvailable,
            requestedMode = requestedMode,
            effectiveMode = effectiveMode,
        )

        fun failed(
            message: String,
            requestId: Long? = null,
            scene: String? = null,
            executionMode: AsyncRequestExecutionMode? = null,
            detailMessage: String? = null,
            startedAtEpochMillis: Long? = null,
            finishedAtEpochMillis: Long = System.currentTimeMillis(),
            streaming: Boolean = false,
            streamPhase: String? = null,
            previewText: String? = null,
            previewUpdatedAtEpochMillis: Long? = null,
            finalizingStructuredResult: Boolean = false,
            providerLabel: String? = null,
            model: String? = null,
            endpointSummary: String? = null,
            promptPreviewAvailable: Boolean = false,
            requestedMode: QaMode? = null,
            effectiveMode: QaMode? = null,
        ) = terminal(
            phase = AsyncRequestPhase.FAILED,
            message = message,
            requestId = requestId,
            scene = scene,
            executionMode = executionMode,
            detailMessage = detailMessage,
            startedAtEpochMillis = startedAtEpochMillis,
            finishedAtEpochMillis = finishedAtEpochMillis,
            streaming = streaming,
            streamPhase = streamPhase,
            previewText = previewText,
            previewUpdatedAtEpochMillis = previewUpdatedAtEpochMillis,
            finalizingStructuredResult = finalizingStructuredResult,
            providerLabel = providerLabel,
            model = model,
            endpointSummary = endpointSummary,
            promptPreviewAvailable = promptPreviewAvailable,
            requestedMode = requestedMode,
            effectiveMode = effectiveMode,
        )

        fun timedOut(
            message: String,
            requestId: Long? = null,
            scene: String? = null,
            executionMode: AsyncRequestExecutionMode? = null,
            detailMessage: String? = null,
            startedAtEpochMillis: Long? = null,
            finishedAtEpochMillis: Long = System.currentTimeMillis(),
            streaming: Boolean = false,
            streamPhase: String? = null,
            previewText: String? = null,
            previewUpdatedAtEpochMillis: Long? = null,
            finalizingStructuredResult: Boolean = false,
            providerLabel: String? = null,
            model: String? = null,
            endpointSummary: String? = null,
            promptPreviewAvailable: Boolean = false,
            requestedMode: QaMode? = null,
            effectiveMode: QaMode? = null,
        ) = terminal(
            phase = AsyncRequestPhase.TIMED_OUT,
            message = message,
            requestId = requestId,
            scene = scene,
            executionMode = executionMode,
            detailMessage = detailMessage,
            startedAtEpochMillis = startedAtEpochMillis,
            finishedAtEpochMillis = finishedAtEpochMillis,
            streaming = streaming,
            streamPhase = streamPhase,
            previewText = previewText,
            previewUpdatedAtEpochMillis = previewUpdatedAtEpochMillis,
            finalizingStructuredResult = finalizingStructuredResult,
            providerLabel = providerLabel,
            model = model,
            endpointSummary = endpointSummary,
            promptPreviewAvailable = promptPreviewAvailable,
            requestedMode = requestedMode,
            effectiveMode = effectiveMode,
        )

        private fun terminal(
            phase: AsyncRequestPhase,
            message: String,
            requestId: Long?,
            scene: String?,
            executionMode: AsyncRequestExecutionMode?,
            detailMessage: String?,
            startedAtEpochMillis: Long?,
            finishedAtEpochMillis: Long,
            streaming: Boolean,
            streamPhase: String?,
            previewText: String?,
            previewUpdatedAtEpochMillis: Long?,
            finalizingStructuredResult: Boolean,
            providerLabel: String?,
            model: String?,
            endpointSummary: String?,
            promptPreviewAvailable: Boolean,
            requestedMode: QaMode?,
            effectiveMode: QaMode?,
        ) = AsyncRequestState(
            phase = phase,
            requestId = requestId,
            scene = scene,
            executionMode = executionMode,
            errorMessage = message,
            detailMessage = detailMessage,
            startedAtEpochMillis = startedAtEpochMillis,
            finishedAtEpochMillis = finishedAtEpochMillis,
            streaming = streaming,
            streamPhase = streamPhase,
            previewText = previewText,
            previewUpdatedAtEpochMillis = previewUpdatedAtEpochMillis,
            finalizingStructuredResult = finalizingStructuredResult,
            providerLabel = providerLabel,
            model = model,
            endpointSummary = endpointSummary,
            promptPreviewAvailable = promptPreviewAvailable,
            requestedMode = requestedMode,
            effectiveMode = effectiveMode,
        )
    }
}
